package exporter

// Physical ability icon assets from https://collegefootball.gg/abilities/
var physicalAbilityAssets = map[string]struct{ Slug, Ext string }{
	"360": {Slug: "360", Ext: "webp"},
	"50/50": {Slug: "50-50", Ext: "png"},
	"Aftershock": {Slug: "aftershock", Ext: "png"},
	"Arm Bar": {Slug: "arm-bar", Ext: "png"},
	"Balanced": {Slug: "balanced", Ext: "png"},
	"Ball Security": {Slug: "ball-security", Ext: "webp"},
	"Ballhawk": {Slug: "ballhawk", Ext: "png"},
	"Battering Ram": {Slug: "battering-ram", Ext: "webp"},
	"Best Friend": {Slug: "best-friend", Ext: "png"},
	"Blanket Coverage": {Slug: "blanket-coverage", Ext: "png"},
	"Blow Up": {Slug: "blow-up", Ext: "png"},
	"Bouncer": {Slug: "bouncer", Ext: "png"},
	"Chip Shot": {Slug: "chip-shot", Ext: "png"},
	"Clear Headed": {Slug: "clear-headed", Ext: "png"},
	"Clutch Kicker": {Slug: "clutch-kicker", Ext: "png"},
	"Coffin Corner": {Slug: "coffin-corner", Ext: "png"},
	"Cutter": {Slug: "cutter", Ext: "png"},
	"Deep Range": {Slug: "deep-range", Ext: "png"},
	"Defensive Rally": {Slug: "defensive-rally", Ext: "png"},
	"Dot!": {Slug: "dot", Ext: "png"},
	"Double Dip": {Slug: "double-dip", Ext: "png"},
	"Downhill": {Slug: "downhill", Ext: "webp"},
	"Duress": {Slug: "duress", Ext: "png"},
	"Extender": {Slug: "extender", Ext: "png"},
	"Fan Favorite": {Slug: "fan-favorite", Ext: "png"},
	"Field General": {Slug: "field-general", Ext: "png"},
	"Grip Breaker": {Slug: "grip-breaker", Ext: "png"},
	"Ground N Pound": {Slug: "ground-n-pound", Ext: "png"},
	"Hammer": {Slug: "hammer", Ext: "png"},
	"Headfirst": {Slug: "headfirst", Ext: "png"},
	"Headstrong": {Slug: "headstrong", Ext: "png"},
	"Hot Head": {Slug: "hot-head", Ext: "webp"},
	"House Call": {Slug: "house-call", Ext: "png"},
	"Inside Disruptor": {Slug: "inside-disruptor", Ext: "png"},
	"Inside Shield": {Slug: "inside-shield", Ext: "png"},
	"Jammer": {Slug: "jammer", Ext: "png"},
	"Knockout": {Slug: "knockout", Ext: "png"},
	"Lay Out": {Slug: "lay-out", Ext: "png"},
	"Legion": {Slug: "legion", Ext: "png"},
	"Magician": {Slug: "magician", Ext: "png"},
	"Mega Leg": {Slug: "mega-leg", Ext: "png"},
	"Mobile Deadeye": {Slug: "mobile-deadeye", Ext: "png"},
	"Mobile Resistance": {Slug: "mobile-resistance", Ext: "png"},
	"Off Platform": {Slug: "off-platform", Ext: "png"},
	"Offensive Rally": {Slug: "offensive-rally", Ext: "png"},
	"On Time": {Slug: "on-time", Ext: "png"},
	"Option Disruptor": {Slug: "option-disruptor-2", Ext: "png"},
	"Option King": {Slug: "option-king", Ext: "png"},
	"Option Shield": {Slug: "option-shield", Ext: "png"},
	"Outside Disruptor": {Slug: "outside-disruptor-2", Ext: "png"},
	"Outside Shield": {Slug: "outside-shield", Ext: "png"},
	"PA Shield": {Slug: "pa-shield", Ext: "png"},
	"Pocket Disruptor": {Slug: "pocket-disruptor", Ext: "png"},
	"Pocket Shield": {Slug: "pocket-shield", Ext: "png"},
	"Press Pro": {Slug: "press-pro", Ext: "png"},
	"Pull Down": {Slug: "pull-down", Ext: "png"},
	"Quick Drop": {Slug: "quick-drop", Ext: "png"},
	"Quick Jump": {Slug: "quick-jump", Ext: "png"},
	"Quick Step": {Slug: "quick-step", Ext: "png"},
	"Recoup": {Slug: "recoup", Ext: "png"},
	"Resistance": {Slug: "resistance", Ext: "png"},
	"Road Dog": {Slug: "road-dog", Ext: "png"},
	"Robber": {Slug: "robber", Ext: "png"},
	"Safety Valve": {Slug: "safety-valve", Ext: "png"},
	"Screen Enforcer": {Slug: "screen-enforcer", Ext: "png"},
	"Second Level": {Slug: "second-level", Ext: "png"},
	"Shifty": {Slug: "shifty", Ext: "png"},
	"Side Step": {Slug: "side-step", Ext: "png"},
	"Sidekick": {Slug: "sidekick", Ext: "png"},
	"Sleight Of Hand": {Slug: "sleight-of-hand", Ext: "png"},
	"Step Up": {Slug: "step-up", Ext: "png"},
	"Strong Grip": {Slug: "strong-grip", Ext: "png"},
	"Sure Hands": {Slug: "sure-hands", Ext: "png"},
	"Take Down": {Slug: "take-down", Ext: "png"},
	"Takeoff": {Slug: "takeoff", Ext: "png"},
	"Team Player": {Slug: "team-player", Ext: "png"},
	"The Natural": {Slug: "the-natural", Ext: "png"},
	"Wear Down": {Slug: "wear-down", Ext: "png"},
	"Winning Time": {Slug: "winning-time", Ext: "png"},
	"Workhorse": {Slug: "workhorse", Ext: "png"},
	"Wrap Up": {Slug: "wrap-up", Ext: "png"},
	"Ball Hawk": {Slug: "ballhawk", Ext: "png"},
	"Take Off": {Slug: "takeoff", Ext: "png"},
}
